package:
    name: irtk
    version: 1.0

source:
    path: ../../irtk

build:
    number: 0
    
requirements:
    build:
        - cmake
        - libpng
        - tbb
        - vtk
    run:
        - libpng
        - tbb
        - vtk

about:
    home: https://github.com/BioMedIA/IRTK
    license: BSD
