package:
  name: tbb
  version: "4.0_20110809"

source:
  fn: tbb43_20141023oss_osx.tgz  # [osx]
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/mac/tbb43_20141023oss_osx.tgz  # [osx]
  sha256: 692a0c942a626eb7237485591d73aab298f3624b4348023d66913b73496e3a71  # [osx]
  fn: tbb40_20110809oss_src.tgz  # [linux]
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb40_20110809oss_src.tgz  # [linux]


about:
  home: https://www.threadingbuildingblocks.org/
  license: GPLv2

